var templatehtm = '<div id="page2" class="playing">'
+ '    <div class="header">'
+ '        <a href="explore" class="btn-home"></a>'
+ '        <p class="title">'
+ '            正在播放</p>'
+ '        <a href="javascript:;" class="btn-back"></a>'
+ '    </div>'
+ '    <div class="container">'
+ '        <div class="app-download">'
+ '            <div class="app-info">'
+ '                <p>'
+ '                    喜马拉雅-万能随身听</p>'
+ '                <p>'
+ '                    听新闻，听音乐，听小说，听培训</p>'
+ '                <p>'
+ '                    上下班路上，就听喜马拉雅</p>'
+ '            </div>'
+ '            <div class="app-action">'
+ '                <a href="../www.ximalaya.com/down@tag=wap&client=ios" class="iosBtn"></a><a href="../www.ximalaya.com/down@tag=wap&client=android"'
+ '                    class="androidBtn"></a><a href="../test.ximalaya.com/jt@jt=http_253A_252F_252Fwww.windowsphone.com_252Fzh-cn_252Fstore_252Fapp_252F_2525E5_252596_25259C_2525E9_202587B0028"'
+ '                        class="wpBtn"></a>'
+ '            </div>'
+ '        </div>'
+ '        <div class="player" sound_id="146028" sound_url=""'
+ '            sound_duration="193000">'
+ '            <div class="cover">'
+ '            </div>'
+ '            <div class="pic default">'
+ '                <img id="sound_large_pic" src=""'
+ '                    alt="">'
+ '                <a href="javascript:;" class="player-btn is-paused"></a><a href="javascript:;" class="player-like">'
+ '                </a>'
+ '                <div class="player-progress3">'
+ '                    <span class="time sound_position">00:00</span>'
+ '                    <span class="time time-whole">00:00</span>' 
+ '                    <div class="player_progressbar is-drawed">'
+ '                        <div class="player_wavebox" sound_wave=""'
+ '                            sound_uploadid="u_36028">'
+ '                            <div class="player_backgroundbar">'
+ '                                <canvas width="320" height="20"></canvas>'
+ '                            </div>'
+ '                            <div class="player_playbar" style="width: 0;">'
+ '                                <canvas width="320" height="20"></canvas>'
+ '                            </div>'
+ '                        </div>'
+ '                    </div>'
+ '                </div>'
+ '            </div>'
+ '            <div id="comment"></div>'
+ '            <div class="app-download">'
+ '                <div class="app-info">'
+ '                    <p>'
+ '                        喜马拉雅-万能随身听</p>'
+ '                    <p>'
+ '                        听新闻，听音乐，听小说，听培训</p>'
+ '                    <p>'
+ '                        上下班路上，就听喜马拉雅</p>'
+ '                </div>'
+ '                <div class="app-action">'
+ '                    <a href="../www.ximalaya.com/down@tag=wap&client=ios" class="iosBtn"></a><a href="../www.ximalaya.com/down@tag=wap&client=android"'
+ '                        class="androidBtn"></a><a href="../test.ximalaya.com/jt@jt=http_253A_252F_252Fwww.windowsphone.com_252Fzh-cn_252Fstore_252Fapp_252F_2525E5_252596_25259C_2525E9_202587B0028"'
+ '                            class="wpBtn"></a>'
+ '                </div>'
+ '            </div>'
+ '        </div>'
+ '    </div>'
+ '    <div class="footer">'
+ '        <nav>'
+ '        <a href="explore">首页</a>'
+ '        <a href="download">下载客户端</a>'
+ '        <a href="contact">联系我们</a>'
+ '      </nav>'
+ '    </div>'
+ '</div>';
